# åŸºæœ¬é…ç½®
mixed-port: 7890
redir-port: 9797
tproxy-port: 9898
ipv6: true
mode: Rule
allow-lan: true
unified-delay: true
tcp-concurrent: true
log-level: silent
bind-address: "*"
find-process-mode: strict
external-controller: 0.0.0.0:9090
external-ui-url: "https://v6.gh-proxy.com/https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages-no-fonts.zip"
external-ui: "dashboard"
secret: ""

# è®¢é˜…å¥åº·æ£€æŸ¥
p: &p
  type: http
  interval: 86400
  health-check:
    enable: true
    url: 'http://connectivitycheck.platform.hicloud.com/generate_204'
    interval: 14400
    timeout: 5000
    lazy: true
  proxy: è®¢é˜…æ›´æ–°
  exclude-filter: '(?i)å®˜ç½‘|é‚€è¯·|åˆ°æœŸ|æµé‡|æ›´æ–°|éªŒè¯|å‰©ä½™|é¢‘é“|é•¿æœŸ|æ¨å¹¿|åˆ†äº«|å‘¨æœŸ|æˆ‘çš„'
  header:
      User-Agent:
      - "ClashMetaForAndroid/2.11.2.Meta"

# ä»£ç†ç»„å¥åº·æ£€æŸ¥
q: &q
    interval: 7200
    lazy: true
    timeout: 5000
    url: 'http://connectivitycheck.platform.hicloud.com/generate_204'

# è®¢é˜…åœ°å€ç›¸å…³
a: &a
  use:
  - proxy1
#  - proxy2

proxy-providers:
  proxy1:
    <<: *p
    override:
      additional-prefix: "Main:" #èŠ‚ç‚¹å‰ç¼€å
    path: ./proxy_provider/proxy1.yaml
    url: ""
  
  proxy2:
    <<: *p
    override:
      additional-prefix: "sec:" #èŠ‚ç‚¹å‰ç¼€å
    path: ./proxy_provider/proxy2.yaml
    url: ""

# èŠ‚ç‚¹è®°å¿†
profile:
  store-selected: true
  store-fake-ip: true

# å—…æ¢æ¨¡å—
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
    TLS:
      ports: [443, 5228, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "+.v2ex.com"
  skip-domain: # å¦‚é‡éœ€å†…éƒ¨é€šä¿¡çš„åº”ç”¨è¯·æ”¾è¡Œè¯¥åŸŸå
    - "Mijia Cloud"

# ç½‘å¡æ¨¡å—
tun:
  exclude-uid: []
  include-uid: [10133,10155,10183,10219,10235,10237,10239,10240,10241,10284,10286,10291,10293,10316,10320,10330,10338,10345,10350,10354,10366,10373,10382,10383,10393,10404,10408,10413,10414,10417,10419,10420,10429,10430,10435,10439,10441,10444,10446,10449,10450,10481,10520,10543]
  enable: true  # true å¼€ # false é»˜è®¤å…³
  device: Meta
  stack: gvisor
  dns-hijack:
    - any:53
    - tcp://any:53
  udp-timeout: 300
  auto-route: true
  strict-route: true
  auto-redirect: false
  auto-detect-interface: true
  exclude-package:

hosts: 
    services.googleapis.cn: services.googleapis.com


# DNSæ¨¡å—
dns:
  enable: true
  ipv6: true
  cache-algorithm: arc
  prefer-h3: true
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-range6: fdfe:dcba:9876::1/64
  fake-ip-filter:
    - "RULE-SET:CN_åŸŸ"
    - "RULE-SET:Fake-IP-Filter"
    - "RULE-SET:GoogleFCM_åŸŸ"
  default-nameserver:
    - 223.5.5.5
    - 1.12.12.12
    - 8.8.8.8
    - 1.1.1.1
  direct-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  proxy-server-nameserver:
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
  nameserver-policy:
    "RULE-SET:CN_åŸŸ":
      - https://dns.alidns.com/dns-query
      - https://doh.pub/dns-query
  nameserver:
    - https://cloudflare-dns.com/dns-query
    - https://dns.google/dns-query

# ç‰¹æ®Šä»£ç†èŠ‚ç‚¹å®šä¹‰
proxies:
  - {name: ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿, type: direct, udp: true,ip-version: ipv6-prefer}
  - {name: â›” æ‹’ç»è¿æ¥, type: reject}
  - {name: ğŸŒ DNS_Hijack, type: dns}

# ä»£ç†ç»„é€šç”¨é…ç½®
proxy_groups: &proxy_groups
    type: select
    proxies:
      - æ€»æ¨¡å¼
      - ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿
      - å»¶è¿Ÿæœ€ä½
      - æ•…éšœè½¬ç§»
      - è´Ÿè½½å‡è¡¡
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ‰‹åŠ¨é€‰æ‹©
      - â›” æ‹’ç»è¿æ¥

# ä»£ç†ç»„é…ç½®
proxy-groups:
  - name: æ€»æ¨¡å¼
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Main.png"
    type: select
    proxies:
      - å»¶è¿Ÿæœ€ä½
      - æ•…éšœè½¬ç§»
      - è´Ÿè½½å‡è¡¡
      - é¦™æ¸¯èŠ‚ç‚¹
      - å°æ¹¾èŠ‚ç‚¹
      - ç‹®åŸèŠ‚ç‚¹
      - æ—¥æœ¬èŠ‚ç‚¹
      - ç¾å›½èŠ‚ç‚¹
      - æ‰‹åŠ¨é€‰æ‹©

  - name: è®¢é˜…æ›´æ–°
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Update.png"
    type: select
    proxies:
      - ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿
      - æ€»æ¨¡å¼

  # åº”ç”¨åˆ†æµç­–ç•¥
  - name: Microsoft
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Microsoft.png"
    <<: *proxy_groups

  - name: Telegram
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Telegram.png"
    <<: *proxy_groups

  - name: Discord
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Discord.png"
    <<: *proxy_groups

  - name: TikTok
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/TikTok.png"
    <<: *proxy_groups

  - name: YouTube
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/YouTube.png"
    <<: *proxy_groups

  - name: Instagram
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Instagram.png"
    <<: *proxy_groups

  - name: Google
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Google.png"
    <<: *proxy_groups

  - name: GoogleFCM
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/GoogleFCM.png"
    <<: *proxy_groups

  - name: AI
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/AI.png"
    <<: *proxy_groups

  - name: GitHub
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/GitHub.png"
    <<: *proxy_groups

  - name: Twitter(X)
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Twitter.png"
    <<: *proxy_groups

  - name: å›½å†…ç›´è¿åå•
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/GNZL.png"
    <<: *proxy_groups

  - name: æµ·å¤–ä»£ç†åå•
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/HWDL.png"
    <<: *proxy_groups

  - name: ç¦æ­¢è®¿é—®åå•
    icon: "https://cdn.jsdelivr.net/gh/MoGuangYu/Surfing@rm/Home/icon/User.svg"
    <<: *proxy_groups

  - name: å¹¿å‘Šæ‹¦æˆª
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/GGLJ.png"
    type: select
    proxies:
      - PASS
      - â›” æ‹’ç»è¿æ¥
      - ğŸŒ DNS_Hijack
      - REJECT-DROP

  - name: WebRTC
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/WebRTC.png"
    type: select
    proxies:
      - PASS
      - â›” æ‹’ç»è¿æ¥
      - ğŸŒ DNS_Hijack
      - REJECT-DROP

  - name: æ¼ç½‘ä¹‹é±¼
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/LWZY.png"
    <<: *proxy_groups
  
  # -------- è‡ªåŠ¨ç­–ç•¥ç»„ --------
  - name: å»¶è¿Ÿæœ€ä½
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/YCZD.png"
    type: url-test
    <<: [*q,*a]

  - name: æ•…éšœè½¬ç§»
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/GZZY.png"
    type: fallback
    <<: [*q,*a]

  - name: è´Ÿè½½å‡è¡¡
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/FZJH.png"
    type: load-balance
    strategy: round-robin
    <<: [*q,*a]

  # -------- åœ°åŒºèŠ‚ç‚¹åˆ†ç»„ --------
  - name: ç‹®åŸèŠ‚ç‚¹
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Singapore.png"
    filter: "^(?=.*(æ–°åŠ å¡|å¡|ç‹®åŸ|SG|Singapore)).*$"
    type: url-test
    <<: [*q,*a]

  - name: ç¾å›½èŠ‚ç‚¹
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/UnitedStates.png"
    filter: "^(?=.*(ç¾|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥|America|US|United States)).*$"
    type: url-test
    <<: [*q,*a]

  - name: é¦™æ¸¯èŠ‚ç‚¹
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/HongKong.png"
    filter: "^(?=.*(æ¸¯|HK|hk|Hong Kong|HongKong|hongkong)).*$"
    type: url-test
    <<: [*q,*a]

  - name: æ—¥æœ¬èŠ‚ç‚¹
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Japan.png"
    filter: "^(?=.*(æ—¥æœ¬|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|JP|Japan)).*$"
    type: url-test
    <<: [*q,*a]

  - name: å°æ¹¾èŠ‚ç‚¹
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Taiwan.png"
    filter: "^(?=.*(å°|æ–°åŒ—|å½°åŒ–|TW|Taiwan)).*$"
    type: url-test
    <<: [*q,*a]

  - name: æ‰‹åŠ¨é€‰æ‹©
    icon: "https://v6.gh-proxy.com/https://github.com/musiyun124/mihomo/raw/refs/heads/main/icon2/Select.png"
    type: select
    <<: *a

# ============ è§„åˆ™é›†é”šç‚¹å®šä¹‰ ============
rule-anchor:
  Local: &Local
    {type: file, behavior: classical, format: text}
  YAML: &YAML
    {type: http, behavior: classical, format: yaml, interval: 86400}
  Classical: &Classical
    {type: http, behavior: classical, format: text, interval: 86400}
  IPCIDR: &IPCIDR
    {type: http, behavior: ipcidr, format: mrs, interval: 86400}
  Domain: &Domain
    {type: http, behavior: domain, format: mrs, interval: 86400}

# ============ è§„åˆ™é›†é…ç½® ============
rule-providers:
  ç›´è¿åå•: # æœ¬åœ°è‡ªå®šä¹‰ç›´è¿åŸŸååˆ—è¡¨  éœ€åœ¨githubè‡ªå·±åˆ›å»ºæ–‡ä»¶å¹¶æ·»åŠ è§„åˆ™,rawé“¾æ¥
    <<: *Classical
    path: ./rules/direct.list
    url: "https://raw.githubusercontent.com/phoukn/x6p-note/refs/heads/main/surfing/direct_clash.list"

  ä»£ç†åå•: # æœ¬åœ°è‡ªå®šä¹‰ä»£ç†åŸŸååˆ—è¡¨  éœ€åœ¨githubè‡ªå·±åˆ›å»ºæ–‡ä»¶å¹¶æ·»åŠ è§„åˆ™,rawé“¾æ¥
    <<: *Classical
    path: ./rules/proxy.list
    url: "https://raw.githubusercontent.com/phoukn/x6p-note/refs/heads/main/surfing/proxy_clash.list"

  ç¦æ­¢åå•: # æœ¬åœ°è‡ªå®šä¹‰é™æ­¢åŸŸååˆ—è¡¨  éœ€åœ¨githubè‡ªå·±åˆ›å»ºæ–‡ä»¶å¹¶æ·»åŠ è§„åˆ™,rawé“¾æ¥
    <<: *Classical
    path: ./rules/block.list
    url: "https://raw.githubusercontent.com/phoukn/x6p-note/refs/heads/main/surfing/block_clash.list" 

  WebRTC_ç«¯/åŸŸ:
    <<: *Classical
    path: ./rules/WebRTC.list
    url: "https://v6.gh-proxy.com/https://github.com/GitMetaio/Surfing/raw/refs/heads/rm/Home/rules/WebRTC.list"

  Fake-IP-Filter:
    <<: *Domain
    path: ./rules/Fake-IP-Filter.mrs
    url: "https://v6.gh-proxy.com/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/fakeip-filter.mrs"

  CN_IP:
    <<: *IPCIDR
    path: ./rules/CN_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"
  CN_åŸŸ:
    <<: *Domain
    path: ./rules/CN_åŸŸ.mrs
    url: "https://v6.gh-proxy.com/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/cn.mrs"

  No-ads-all_åŸŸ:
    <<: *Domain
    path: ./rules/No-ads-all.mrs
    url: "https://v6.gh-proxy.com/https://github.com/TG-Twilight/AWAvenue-Ads-Rule/raw/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.mrs"

  TikTok_åŸŸ:
    <<: *Domain
    path: ./rules/TikTok.mrs
    url: "https://v6.gh-proxy.com/https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/domain/tiktok.mrs"

  Telegram_åŸŸ:
    <<: *Domain
    path: ./rules/Telegram.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/telegram.mrs"
  Telegram_IP:
    <<: *IPCIDR
    path: ./rules/Telegram_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/telegram.mrs"

  YouTube_åŸŸ:
    <<: *Domain
    path: ./rules/YouTube.mrs
    url: "https://v6.gh-proxy.com/https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/domain/youtube.mrs"
  YouTube_IP:
    <<: *IPCIDR
    path: ./rules/YouTube_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/peiyingyao/Rule-for-OCD/raw/refs/heads/master/rule/Clash/YouTube/YouTube_OCD_IP.mrs"

  Google_åŸŸ:
    <<: *Domain
    path: ./rules/Google.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/google.mrs"
  Google_IP:
    <<: *IPCIDR
    path: ./rules/Google_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geoip/google.mrs"

  GoogleFCM_åŸŸ:
    <<: *Domain
    path: ./rules/GoogleFCM.mrs
    url: "https://v6.gh-proxy.com/https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/domain/googlefcm.mrs"

  Microsoft_åŸŸ:
    <<: *Domain
    path: ./rules/Microsoft.mrs
    url: "https://v6.gh-proxy.com/https://github.com/QuixoticHeart/rule-set/raw/refs/heads/ruleset/meta/domain/microsoft.mrs"

  AI_åŸŸ:
    <<: *Domain
    path: ./rules/AI.mrs
    url: "https://v6.gh-proxy.com/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/ai.mrs"
  AI_IP:
    <<: *IPCIDR
    path: ./rules/AI_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geoip/ai.mrs"

  Instagram_åŸŸ:
    <<: *Domain
    path: ./rules/Instagram.mrs
    url: "https://v6.gh-proxy.com/https://github.com/peiyingyao/Rule-for-OCD/raw/refs/heads/master/rule/Clash/Instagram/Instagram_OCD_Domain.mrs"

  Discord_åŸŸ:
    <<: *Domain
    path: ./rules/Discord.mrs
    url: "https://v6.gh-proxy.com/https://github.com/peiyingyao/Rule-for-OCD/raw/refs/heads/master/rule/Clash/Discord/Discord_OCD_Domain.mrs"

  GitHub_åŸŸ:
    <<: *Domain
    path: ./rules/GitHub.mrs
    url: "https://v6.gh-proxy.com/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo-lite/geosite/github.mrs"

  Twitter_åŸŸ:
    <<: *Domain
    path: ./rules/Twitter.mrs
    url: "https://v6.gh-proxy.com/https://github.com/peiyingyao/Rule-for-OCD/raw/refs/heads/master/rule/Clash/Twitter/Twitter_OCD_Domain.mrs"
  Twitter_IP:
    <<: *IPCIDR
    path: ./rules/Twitter_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/peiyingyao/Rule-for-OCD/raw/refs/heads/master/rule/Clash/Twitter/Twitter_OCD_IP.mrs"

  Private_åŸŸ:
    <<: *Domain
    path: ./rules/LAN.mrs
    url: "https://v6.gh-proxy.com/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/private.mrs"
  Private_IP:
    <<: *IPCIDR
    path: ./rules/Private_IP.mrs
    url: "https://v6.gh-proxy.com/https://github.com/DustinWin/ruleset_geodata/raw/refs/heads/mihomo-ruleset/privateip.mrs"

# ============ è·¯ç”±è§„åˆ™ ============
# è§„åˆ™ä¼˜å…ˆçº§ï¼šä»ä¸Šåˆ°ä¸‹ä¾æ¬¡åŒ¹é…ï¼Œå‘½ä¸­å³åœæ­¢
rules:
  # -------- DNS ç›¸å…³è§„åˆ™ --------
  - DST-PORT,53,ğŸŒ DNS_Hijack

  # -------- è‡ªå®šä¹‰è§„åˆ™ä¼˜å…ˆ --------
  - RULE-SET,ç¦æ­¢åå•,ç¦æ­¢è®¿é—®åå•
  - RULE-SET,ç›´è¿åå•,å›½å†…ç›´è¿åå•
  - RULE-SET,ä»£ç†åå•,æµ·å¤–ä»£ç†åå•

  # -------- åŠŸèƒ½æ€§è§„åˆ™ --------
  - RULE-SET,WebRTC_ç«¯/åŸŸ,WebRTC
  - RULE-SET,No-ads-all_åŸŸ,å¹¿å‘Šæ‹¦æˆª

  # -------- æœ¬åœ°ç½‘ç»œè§„åˆ™ --------
  - RULE-SET,Private_åŸŸ,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿
  - RULE-SET,Private_IP,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿,no-resolve
  
  - RULE-SET,GitHub_åŸŸ,GitHub
  - RULE-SET,Discord_åŸŸ,Discord
  - RULE-SET,TikTok_åŸŸ,TikTok

  - RULE-SET,Twitter_åŸŸ,Twitter(X)
  - RULE-SET,Twitter_IP,Twitter(X),no-resolve

  - RULE-SET,AI_åŸŸ,AI
  - RULE-SET,AI_IP,AI,no-resolve
  - PROCESS-NAME,com.openai.chatgpt,AI

  - DOMAIN-KEYWORD,mtalk.google,GoogleFCM

  - RULE-SET,YouTube_åŸŸ,YouTube
  - RULE-SET,YouTube_IP,YouTube,no-resolve

  - RULE-SET,Google_åŸŸ,Google
  - RULE-SET,Google_IP,Google,no-resolve

  - PROCESS-NAME,com.instagram.android,Instagram
  - RULE-SET,Instagram_åŸŸ,Instagram

  - RULE-SET,Microsoft_åŸŸ,Microsoft

  - RULE-SET,Telegram_åŸŸ,Telegram
  - RULE-SET,Telegram_IP,Telegram,no-resolve

  - RULE-SET,Facebook_åŸŸ,Facebook
  - RULE-SET,Facebook_IP,Facebook,no-resolve

  - DOMAIN,browserleaks.com,æ¼ç½‘ä¹‹é±¼
  
  # -------- ä¸­å›½å¤§é™†è§„åˆ™ --------
  - RULE-SET,CN_åŸŸ,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿
  - RULE-SET,CN_IP,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿,no-resolve
  - DOMAIN,time.is,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿
  - DOMAIN-SUFFIX,ntp.org,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿
  - DOMAIN-KEYWORD,v6.gh-proxy,ğŸ‡¨ğŸ‡³ æœ¬åœ°ç›´è¿

  # å…œåº•è§„åˆ™
  - MATCH,æ¼ç½‘ä¹‹é±¼
